# Generated by Django 6.0.3 on 2026-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='major',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
