# Generated by Django 6.0.3 on 2026-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='internship_type',
            field=models.CharField(choices=[('BTS', 'BTS (30 months)'), ('BT', 'BT (24 months)'), ('CAP', 'CAP (18 months)'), ('CMP', 'CMP (12 months)'), ('UNIVERSITY', 'Stagiaire Universitaire (Max 2 months)')], default='BTS', max_length=20),
        ),
    ]
