# Generated by Django 6.0.3 on 2026-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internprofile_internship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
