# Generated by Django 6.0.3 on 2026-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_submission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
